### ISSUE TITLE
Error an exception occurred while executing insert into

### ISSUE THREAD

**Issue by braianj** [xiidea/EasyAuditBundle#14]
I got this error when it try to insert into the audit_lo table

`An exception occurred while executing 'INSERT INTO audit_log (id, type_id, type, description, event_time, user, impersonatingUser, ip) VALUES (?, ?, ?, ?, ?, ?, ?, ?)' with params [5, "security.interactive_login", "security.interactive_login", "security.interactive_login", "2017-11-22 12:56:48", "bmellor", null, "::1"]:`

and this log

	`Uncaught PHP Exception Doctrine\DBAL\Exception\SyntaxErrorException: "An exception occurred while executing 'INSERT INTO audit_log (id, type_id, type, description, event_time, user, impersonatingUser, ip) VALUES (?, ?, ?, ?, ?, ?, ?, ?)' with params [5, "security.interactive_login", "security.interactive_login", "security.interactive_login", "2017-11-22 12:56:48", "bmellor", null, "::1"]: SQLSTATE[42601]: Syntax error: 7 ERROR: syntax error in or close to «user» LINE 1: ..._log (id, type_id, type, description, event_time, user, impe... ^" at /project/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php line 70`

**Comment by ronisaha** [comment]
Could you please provide some more information. Like:
Symfony version
Php version
EasyAuditBundle version

Best, if you can provide an example project to reproduce the bug.

**Comment by braianj** [comment]
Hi @ronisaha, here goes some info:

- PHP v 7.1.11
- Symfony 3.3.X
- EasyAuditBundle: ^1.4

And the code is the same as the examples

**Comment by ronisaha** [comment]
Could you also share the entity class

**Comment by braianj** [comment]
Also comment that i'm using postgreSQL 9.6

This is my entity

```
<?php

namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Xiidea\EasyAuditBundle\Entity\BaseAuditLog;

/**
 * @ORM\Entity
 * @ORM\Table(name="audit_log")
 */
class AuditLog extends BaseAuditLog
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * Type Of Event(Internal Type ID)
     *
     * @var string
     * @ORM\Column(name="type_id", type="string", length=200, nullable=false)
     */
    protected $typeId;

    /**
     * Type Of Event
     *
     * @var string
     * @ORM\Column(name="type", type="string", length=200, nullable=true)
     */
    protected $type;

    /**
     * @var string
     * @ORM\Column(name="description", type="string", length=255, nullable=true)
     */
    protected $description;

    /**
     * Time Of Event
     * @var \DateTime
     * @ORM\Column(name="event_time", type="datetime")
     */
    protected $eventTime;

    /**
     * @var string
     * @ORM\Column(name="user", type="string", length=255)
     */
    protected $user;
   
    /**
     * @var string
     * @ORM\Column(name="impersonatingUser", type="string", length=255)
     */
    protected $impersonatingUser;
    
    /**
     * @var string
     * @ORM\Column(name="ip", type="string", length=20, nullable=true)
     */
    protected $ip;    

}
```

And in order to make it work I need it to change the column user for user_name (it seems like user is a reserved name) and to set impersonatingUser as nullable=true, if not this throw me an error.

Now I have an other question, if it's possible, actually 2:

1. I have saved some date but it save `Table has been updated with id = "38"` without saving the real change I make
2. How can I make to show the audit data?

**Comment by hacfi** [comment]
@braianj Yup, `user` is a reserver keyword: https://www.postgresql.org/docs/9.6/static/sql-keywords-appendix.html

**Comment by kl3sk** [comment]
Same issue for ```impersonatingUser```, i had to make it ```nullable``` in order to work properly.

Can someone explain me what is the goal and how works this property ?

**Comment by ronisaha** [comment]
Of course you need to make nullable the **`impersonatingUser`** property as it is an optional property. **`impersonatingUser`** is used when you enable [impersonatingUser](https://symfony.com/doc/current/security/impersonating_user.html) feature. The field will hold the original user value.

**Comment by kl3sk** [comment]
Okay thank you, it sounds obvious
