### ISSUE TITLE
Error when trying to get property that not exist

### ISSUE THREAD

**Issue by braianj** [xiidea/EasyAuditBundle#15]
Hello, I always save the id inside the table. Sometimes it save null because do not have an id. But In a particular table I have a combine primaty key, and the try catch is not working

![captura de pantalla de 2017-12-26 14-52-14](https://user-images.githubusercontent.com/6572776/34361810-871312ba-ea4c-11e7-953a-52c239f4cdd8.png)

![captura de pantalla de 2017-12-26 14-52-39](https://user-images.githubusercontent.com/6572776/34361811-8a4e98d2-ea4c-11e7-903d-8c5f1b172a96.png)

What can I do to catch the error and so return null or another value?

**Comment by ronisaha** [comment]
You can override getProperties function to suit your need

**Comment by braianj** [comment]
No need, it works just fine. Te problem is that try catch is not catching, but I catch if the table is the one without id.
