### ISSUE TITLE
Documentation needs to be corrected

### ISSUE THREAD

**Issue by DamienHarper** [xiidea/EasyAuditBundle#16]
In order to track all events for an entity, documentation states to setup configuration as below:
```
xiidea_easy_audit:
    doctrine_entities :
         MyProject\Bundle\MyBundle\Entity\MyEntity: ~
```
This does not work, no event is tracked for MyEntity.

But, setting up configuration as below does work:
```
xiidea_easy_audit:
    doctrine_entities :
         MyProject\Bundle\MyBundle\Entity\MyEntity: []
```
Documentation should be corrected or code adjusted to follow the doc.

**Comment by ronisaha** [comment]
It would be helpful if you could send a pull request.
