### ISSUE TITLE
Symfony 4 incompatibility

### ISSUE THREAD

**Issue by DamienHarper** [xiidea/EasyAuditBundle#17]
When using your bundle in a Symfony 3.4.x project, I get the following deprecated warning:
> User Deprecated: The "annotation_reader" service is private, getting it from the container is deprecated since Symfony 3.2 and will fail in 4.0. You should either make the service public, or stop using the container directly and use dependency injection instead.

https://github.com/xiidea/EasyAuditBundle/blob/154d99e925a6c657f5c0ead5288ebc823ec91f7a/Subscriber/DoctrineSubscriber.php#L131

**Comment by ronisaha** [comment]
Thanks, I'll Look into it, if you can make a pull request, it will be very helpful
