### ISSUE TITLE
Allow PHP 8 in composer.json version constraints.

### ISSUE THREAD

**Issue by moag1000** [xiidea/EasyAuditBundle#48]
Hi,
with PHP 8 being productive now, many people (like me) prepare a version upgrade of both symfony and components. I've not found major issues with using PHP8 on this bundle and would ask to add PHP 8.0 to version constraints.

Cheers

**Comment by ronisaha** [comment]
@moag1000 Have you tried with php8.0? Does the test case passed? Could you make a PR with php 8 in composer and travis config?
