### ISSUE TITLE
Upgraded to Symfony 5

### ISSUE THREAD

**Issue by denis1994** [xiidea/EasyAuditBundle#52]
Hello,

I upgraded to Symfony 5 and also the EasyAuditBundle to v2.0 but I still have this error:

`Argument 1 passed to Xiidea\EasyAuditBundle\Logger\Logger::__construct() must be an instance of Doctrine\Common\Persistence\ManagerRegistry, instance of Doctrine\Bundle\DoctrineBundle\Registry given`

Does anyone have a fix for this ?

**Comment by ronisaha** [comment]
@denis1994  You can update to v2.0.1 or Use some alias for changed package namespace.

**Comment by denis1994** [comment]
It works now with 2.0.1! Thank you!
