### ISSUE TITLE
Get previous value and changed value.

### ISSUE THREAD

**Issue by cAstraea** [xiidea/EasyAuditBundle#53]
How can I access this information ? If it dump the event it's there I think but no way to access it.  All I'm getting is 
array:2 [
  "description" => "Listing has been updated with id = "1085""
  "type" => "Listing updated"

which is not very useful

**Comment by ronisaha** [comment]
The default entity resolver doesn't store the change set. If you like to store the changed data, you can add another field to your AuditLog entity class i.e. changeSet. and implement your own DoctrineEventResolver class extending base given one and set the value there. 

You can read the discussion about it [here](https://github.com/xiidea/EasyAuditBundle/issues/9)
