### ISSUE TITLE
Symfony 6 support?

### ISSUE THREAD

**Issue by mbennett-talentnet** [xiidea/EasyAuditBundle#55]
Any plans to make the bundle compatible with symfony 6?

**Comment by ronisaha** [comment]
Sorry for late reply. I was busy with many things. I'll try to add support for Symfony 6 soon.

**Comment by mbennett-talentnet** [comment]
@ronisaha psr/log v1 is conflicting with several of the symfony v6 components. Any chance we can get psr/log updated to at least v2?

**Comment by ronisaha** [comment]
@mbennett-talentnet , Could you please try from the master branch and give your observations? Then I'll create a tag.

**Comment by mbennett-talentnet** [comment]
@ronisaha I can confirm master is working as expected in my project based on symfony 6.1.
